# Site settings
title: Gabriel Novakovski Nunes
description: Portfólio Pessoal
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://gnovakovski.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gabriel Novakovski Nunes
user_description: Desenvolvedor de Software desde 2014. Conhecimento em linguagens de programação orientada a objetos, com foco em mobile.
user_title: Desenvolvedor Mobile
email: gabrielnovakovski@gmail.com
twitter_username: gabriel_koski
github_username:  gnovakovski
linkedin_username:  gabrielnovakovski

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
